<?php
declare(strict_types=1);

session_start();
require __DIR__ . '/archive_lib.php';
$_SESSION['csrf_token'] ??= bin2hex(random_bytes(32));

$query = trim((string) ($_GET['q'] ?? ''));
$database = archiveDatabase();
if ($query === '') {
    $documents = $database->query('SELECT id, title, category, tags, original_name, document_date, created_at, length(indexed_text) AS text_size FROM documents ORDER BY created_at DESC LIMIT 50')->fetchAll(PDO::FETCH_ASSOC);
} else {
    $like = '%' . $query . '%';
    $statement = $database->prepare('SELECT id, title, category, tags, original_name, document_date, created_at, length(indexed_text) AS text_size FROM documents WHERE title LIKE ? OR category LIKE ? OR tags LIKE ? OR description LIKE ? OR indexed_text LIKE ? OR original_name LIKE ? ORDER BY created_at DESC LIMIT 100');
    $statement->execute([$like, $like, $like, $like, $like, $like]);
    $documents = $statement->fetchAll(PDO::FETCH_ASSOC);
}
?>
<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Classeur Pro - Archives</title>
<style>
:root{--navy:#102a43;--blue:#1f6feb;--ink:#172b4d;--muted:#61758a;--line:#dce5ef;--bg:#f5f8fc;--soft:#eaf2ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 Inter,"Segoe UI",Arial,sans-serif}.app-header{height:104px;padding:10px 24px;display:flex;align-items:center;position:fixed;z-index:12;inset:0 0 auto;background:#fff;border-bottom:1px solid var(--line)}.app-header img{width:220px;height:80px;object-fit:contain;object-position:left}.app-title{position:absolute;left:50%;transform:translateX(-50%);font-size:22px;font-weight:800}.sidebar{position:fixed;z-index:3;top:104px;bottom:0;width:280px;padding:24px 16px;background:var(--navy);color:#d9e7f5}.brand{height:58px;margin:64px 8px 28px;font-size:18px;font-weight:700}.nav-link{display:block;padding:9px 12px;border-radius:8px;color:inherit;text-decoration:none}.nav-link.active,.nav-link:hover{background:#1c4268}.menu-toggle{position:fixed;z-index:13;top:120px;left:18px;width:44px;height:42px;border:0;border-radius:9px;background:var(--navy);color:#fff;cursor:pointer}main{margin-left:280px;padding:142px clamp(24px,6vw,92px) 54px}.breadcrumb{color:var(--muted);font-size:13px}.breadcrumb a{color:var(--blue);text-decoration:none}h1{margin:28px 0 8px;font-size:36px}.intro{margin:0;color:var(--muted)}.grid{display:grid;grid-template-columns:minmax(300px,390px) 1fr;gap:24px;margin-top:30px}.card{padding:25px;border:1px solid var(--line);border-radius:15px;background:#fff;box-shadow:0 9px 28px rgba(22,52,83,.06)}h2{margin:0 0 12px;font-size:19px}label{display:block;margin-top:15px;font-weight:700}input,textarea{width:100%;margin-top:6px;padding:10px;border:1px solid #b7c8da;border-radius:7px;font:inherit}textarea{min-height:82px;resize:vertical}button{margin-top:20px;padding:11px 16px;border:0;border-radius:7px;background:var(--blue);color:#fff;font-weight:700;cursor:pointer}.search{display:flex;gap:10px;margin-bottom:16px}.search input{margin:0}.search button{margin:0}.notice{padding:11px;border-radius:7px;background:#e9f7ef;color:#167044}.doc{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:15px 0;border-bottom:1px solid var(--line)}.doc:last-child{border-bottom:0}.doc h3{margin:0;font-size:16px}.doc p{margin:3px 0 0;color:var(--muted);font-size:13px}.badge{display:inline-block;padding:2px 7px;border-radius:20px;background:var(--soft);color:#155bc7;font-size:11px;font-weight:700}.open{white-space:nowrap;color:var(--blue);font-weight:700;text-decoration:none}@media(max-width:768px){.app-header{height:92px}.app-header img{width:140px}.app-title{right:18px;left:auto;transform:none;font-size:15px}.sidebar{display:none}main{margin-left:0;padding:116px 20px 36px}.menu-toggle{top:106px}.grid{grid-template-columns:1fr}h1{font-size:30px}}
</style><link rel="stylesheet" href="assets/ui.css?v=6"></head>
<body><?php require __DIR__ . '/ui_nav.php'; ?><main id="main-content" tabindex="-1"><nav class="breadcrumb"><a href="index.php">Accueil</a> / <span>Archives</span></nav><section class="hero"><h1>Archives documentaires</h1><p class="intro">Classez vos documents et retrouvez-les facilement.</p></section><?php if (isset($_GET['success'])): ?><p class="notice">Document archive et indexe avec succes.</p><?php endif; ?><div class="grid"><section class="card"><h2>Archiver un document</h2><form action="archive_store.php" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'], ENT_QUOTES, 'UTF-8') ?>"><label>Document</label><input type="file" name="document" accept="application/pdf,image/*,.docx,.xlsx,.xls" capture="environment" required><p class="intro">PDF et images issus d un scanner, Word ou Excel. Maximum 25 Mo.</p><label>Titre</label><input name="title" maxlength="200" placeholder="Titre du document"><label>Categorie</label><input name="category" maxlength="100" placeholder="Suggestion automatique si vide"><label>Mots cles</label><input name="tags" maxlength="500" placeholder="Exemple : RH, contrat, 2026"><label>Date du document</label><input type="date" name="document_date"><label>Description</label><textarea name="description" maxlength="2000"></textarea><button type="submit">Archiver et indexer</button></form></section><section class="card"><h2>Rechercher dans les archives</h2><form class="search" method="get"><input name="q" value="<?= htmlspecialchars($query, ENT_QUOTES, 'UTF-8') ?>" placeholder="Titre, mot cle, contenu PDF, categorie..."><button>Rechercher</button></form><p class="intro"><?= count($documents) ?> document(s) affiche(s).</p><?php foreach ($documents as $document): ?><article class="doc"><div><h3><?= htmlspecialchars($document['title'], ENT_QUOTES, 'UTF-8') ?> <span class="badge"><?= htmlspecialchars($document['category'], ENT_QUOTES, 'UTF-8') ?></span></h3><p><?= htmlspecialchars($document['original_name'], ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars($document['tags'], ENT_QUOTES, 'UTF-8') ?> · <?= $document['text_size'] > 0 ? 'texte indexe' : 'metadonnees indexees' ?></p></div><a class="open" href="archive_download.php?id=<?= (int) $document['id'] ?>" target="_blank">Ouvrir</a></article><?php endforeach; ?></section></div></main><script src="assets/app.js"></script></body></html>
