// Vérification réelle dans Chrome installé localement, sans dépendance npm.
const { spawn, execFileSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'classeur-ui-'));
const browser = spawn('C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', ['--headless=new', '--remote-debugging-port=0', '--no-first-run', '--no-default-browser-check', '--disable-gpu', '--user-data-dir=' + path.join(folder, 'profile'), 'about:blank'], { windowsHide: true, stdio: 'ignore' });
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
let ws;
(async () => {
    const portFile = path.join(folder, 'profile', 'DevToolsActivePort');
    for (let i = 0; i < 100 && !fs.existsSync(portFile); i++) await pause(100);
    const port = fs.readFileSync(portFile, 'utf8').split('\n')[0];
    const pages = await (await fetch(`http://127.0.0.1:${port}/json`)).json();
    ws = new WebSocket(pages.find(page => page.type === 'page').webSocketDebuggerUrl);
    await new Promise(resolve => ws.addEventListener('open', resolve, { once: true }));
    let id = 0; const pending = new Map(); const errors = [];
    ws.addEventListener('message', event => {
        const data = JSON.parse(event.data);
        if (data.id) { const p = pending.get(data.id); pending.delete(data.id); data.error ? p.reject(data.error) : p.resolve(data.result); }
        if (data.method === 'Runtime.exceptionThrown') errors.push(data.params.exceptionDetails.text + ': ' + (data.params.exceptionDetails.exception?.description || ''));
    });
    const send = (method, params = {}) => new Promise((resolve, reject) => { pending.set(++id, { resolve, reject }); ws.send(JSON.stringify({ id, method, params })); });
    const evaluate = async expression => {
        const result = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
        if (result.exceptionDetails) throw new Error(JSON.stringify(result.exceptionDetails));
        return result.result.value;
    };
    const until = async expression => { for (let i = 0; i < 100; i++) { if (await evaluate(expression)) return; await pause(100); } throw new Error('Timeout: ' + expression + '\n' + await evaluate(`document.querySelector('main').innerText`)); };
    const open = async page => { await send('Page.navigate', { url: 'http://localhost/extraction_excel/' + page }); await until(`location.pathname.endsWith('${page}') && document.readyState === 'complete'`); };
    await send('Runtime.enable'); await send('Page.enable');
    await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false });
    for (const page of ['index.php', 'extraction_mono.php', 'extraction_hybride.php', 'ajout_multi.php', 'impression_mono.php', 'impression_multi.php', 'eclatement.php', 'regroupement.php', 'fusion.php', 'enrichissement.php', 'rapport.php', 'archive.php', 'guide.php']) {
        await open(page);
        assert.equal(await evaluate(`document.querySelectorAll('.sidebar .nav-link').length`), 13, page);
        assert.equal(await evaluate(`document.querySelectorAll('[aria-current="page"]').length`), 1, page);
        assert.equal(await evaluate(`getComputedStyle(document.querySelector('.app-header')).position`), 'fixed', 'En-tête commun : ' + page);
        assert.equal(await evaluate(`getComputedStyle(document.querySelector('.hero')).textAlign`), 'center', 'Présentation centrée : ' + page);
        assert.equal(await evaluate(`document.querySelectorAll('.hero .eyebrow').length`), 0, 'Titre sans surtitre répétitif : ' + page);
        assert.equal(await evaluate(`document.querySelectorAll('.hero p').length <= 1`), true, 'Introduction courte : ' + page);
        assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true, 'Desktop overflow: ' + page);
    }
    await open('enrichissement.php');
    assert.equal(await evaluate(`document.querySelectorAll('.nav-section[open]').length`), 1, 'Seul le groupe actif est ouvert');
    await evaluate(`document.querySelector('.nav-section summary').click()`);
    assert.equal(await evaluate(`document.querySelectorAll('.nav-section[open]').length`), 2, 'Groupe ouvert au clic');
    await evaluate(`document.querySelector('.nav-section summary').click()`);
    assert.equal(await evaluate(`getComputedStyle(document.querySelector('.sidebar')).backgroundColor`), 'rgb(26, 9, 62)', 'Violet du logo');
    fs.writeFileSync(path.join(folder, 'desktop.png'), Buffer.from((await send('Page.captureScreenshot', { captureBeyondViewport: true })).data, 'base64'));
    await evaluate(`document.querySelector('.menu-toggle').click()`);
    assert.equal(await evaluate(`document.querySelector('.menu-toggle').getAttribute('aria-expanded')`), 'false');
    await evaluate(`document.querySelector('.menu-toggle').click()`);
    const fixture = path.join(folder, 'fixture.xlsx');
    execFileSync('C:\\xampp\\php\\php.exe', ['-r', `require 'vendor/autoload.php'; $b = new PhpOffice\\PhpSpreadsheet\\Spreadsheet(); $b->getActiveSheet()->fromArray([['Matricule','Salaire'],['001',125]]); PhpOffice\\PhpSpreadsheet\\IOFactory::createWriter($b,'Xlsx')->save($argv[1]);`, fixture]);
    const upload = async (selector, files) => { const doc = await send('DOM.getDocument'); const node = await send('DOM.querySelector', { nodeId: doc.root.nodeId, selector }); await send('DOM.setFileInputFiles', { nodeId: node.nodeId, files }); };
    const partialFixture = path.join(folder, 'partiel.xlsx');
    execFileSync('C:\\xampp\\php\\php.exe', ['-r', `require 'vendor/autoload.php'; $b = new PhpOffice\\PhpSpreadsheet\\Spreadsheet(); $b->getActiveSheet()->fromArray([['Nom','Identifiant'],['Marie','001']]); PhpOffice\\PhpSpreadsheet\\IOFactory::createWriter($b,'Xlsx')->save($argv[1]);`, partialFixture]);
    await send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: folder });
    await open('guide.php');
    await evaluate(`document.querySelector('a[href="guide_pdf.php"]').click()`);
    for (let i = 0; i < 100 && !fs.existsSync(path.join(folder, 'guide_utilisateur_classeur_pro.pdf')); i++) await pause(100);
    assert.equal(fs.readFileSync(path.join(folder, 'guide_utilisateur_classeur_pro.pdf')).subarray(0,5).toString(), '%PDF-', 'Téléchargement direct du guide');
    fs.writeFileSync(path.join(folder, 'guide.png'), Buffer.from((await send('Page.captureScreenshot', { captureBeyondViewport: false })).data, 'base64'));
    for (const route of ['index.php', 'extraction_mono.php']) {
        await open(route);
        assert.equal(await evaluate(`document.querySelector('#extraction-advanced').open`), false, 'Options repliées au départ');
        assert.equal(await evaluate(`document.querySelector('[name=output_mode]').value`), route === 'index.php' ? 'multi' : 'mono');
        assert.equal(await evaluate(`document.querySelector('[name=output_mode]').checkVisibility()`), false, 'Choix de sortie replié');
        await upload('#global', [fixture]); await upload('#partiel', [partialFixture]);
        await until(`document.querySelector('#global_status').dataset.tone === 'success' && document.querySelector('#partiel_status').dataset.tone === 'success'`);
        assert.equal(await evaluate(`document.querySelectorAll('#global-columns input:checked').length`), 2, 'Toutes les colonnes par défaut');
        await evaluate(`for (const [id, index] of [['global_key',1],['partiel_key',2]]) { const s = document.getElementById(id); s.selectedIndex=index; s.dispatchEvent(new Event('change',{bubbles:true})); }`);
        assert.equal(await evaluate(`document.querySelector('#extraction-submit').disabled`), false);
        assert.equal(await evaluate(`document.querySelector('#insert_before').value`), '', 'Ajout en fin par défaut');
        if (route === 'index.php') fs.writeFileSync(path.join(folder, 'extraction.png'), Buffer.from((await send('Page.captureScreenshot', { captureBeyondViewport: true })).data, 'base64'));
        await evaluate(`document.querySelector('#extraction-submit').click()`);
        await until(`document.querySelector('#extraction-status').dataset.tone === 'success'`);
        assert.match(await evaluate(`document.querySelector('#extraction-status').textContent`), /1 ligne\(s\) trouvée/);
        assert.equal(await evaluate(`document.querySelector('#extraction-advanced').open`), false, 'Extraction sans ouvrir les options');
        await evaluate(`document.querySelector('#extraction-advanced > summary').click()`);
        assert.equal(await evaluate(`document.querySelector('#insert_before').checkVisibility()`), true);
        if (route === 'index.php') assert.equal(await evaluate(`document.querySelector('#output_mode').checkVisibility()`), true);
        await evaluate(`document.querySelector('#append_missing').value='1'`);
        await evaluate(`document.querySelector('#select-none').click()`);
        assert.equal(await evaluate(`document.querySelectorAll('#global-columns input:checked').length`), 0);
        await evaluate(`const checkbox = document.querySelectorAll('#global-columns input')[1];checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}));const position=document.querySelector('#insert_before');position.selectedIndex=1;position.dispatchEvent(new Event('change',{bubbles:true}))`);
        assert.match(await evaluate(`document.querySelector('#column-preview').textContent`), /^1\. Salaire2\. Nom3\. Identifiant/);
        await evaluate(`document.querySelector('#extraction-advanced > summary').click()`);
        assert.equal(await evaluate(`document.querySelector('#extraction-advanced').open`), false);
        await evaluate(`document.querySelector('#extraction-submit').click()`);
        await until(`document.querySelector('#extraction-status').dataset.tone === 'success'`);
        assert.match(await evaluate(`document.querySelector('#extraction-status').textContent`), /1 ligne\(s\) trouvée/);
        assert.equal(await evaluate(`document.querySelector('#global').files.length`), 1);
    }
    await open('extraction_hybride.php');
    await upload('#global', [fixture]); await upload('#partiel', [partialFixture]);
    await until(`document.querySelector('#global_status').dataset.tone === 'success' && document.querySelector('#partiel_status').dataset.tone === 'success'`);
    await evaluate(`document.querySelector('#match_sheets').value='1';document.querySelector('#match_sheets').dispatchEvent(new Event('change',{bubbles:true}));for(const id of ['global_key','partiel_key']) { const s=document.getElementById(id);s.selectedIndex=id==='global_key'?1:2;s.dispatchEvent(new Event('change',{bubbles:true})); } document.querySelector('#extraction-submit').click()`);
    await until(`document.querySelector('#extraction-status').dataset.tone === 'success'`);
    const duplicateFixture = path.join(folder,'duplicates.xlsx');
    execFileSync('C:\\xampp\\php\\php.exe',['-r',`require 'vendor/autoload.php'; $b=new PhpOffice\\PhpSpreadsheet\\Spreadsheet();$b->getActiveSheet()->fromArray([['Matricule','Salaire'],['001',null],['001',250]]);PhpOffice\\PhpSpreadsheet\\IOFactory::createWriter($b,'Xlsx')->save($argv[1]);`,duplicateFixture]);
    for (const route of ['ajout_multi.php','enrichissement.php']) {
        await open(route); await upload('#origin',[fixture]); await upload('#extra',[duplicateFixture]);
        if(route==='ajout_multi.php') assert.equal(await evaluate(`document.querySelector('#multi-options').open`),false,'Options Ajout multi repliées');
        await until(`document.querySelector('#origin_status').dataset.tone==='success' && document.querySelector('#extra_status').dataset.tone==='success'`);
        const columnsId=route==='ajout_multi.php'?'add_columns':'add_column';
        assert.equal(await evaluate(`document.querySelector('#${columnsId}').hidden`),true,'Liste multiple remplacée');
        await until(`document.querySelectorAll('#${columnsId}-choices input:checked').length===2`);
        await evaluate(`document.querySelector('#${columnsId}-choice-1').click()`);
        assert.equal(await evaluate(`document.querySelector('#${columnsId}').selectedOptions.length`),1,'Décocher conserve les autres choix');
        await evaluate(`document.querySelector('#${columnsId}-choices button').click()`);
        assert.equal(await evaluate(`document.querySelector('#${columnsId}').selectedOptions.length`),2,'Tout cocher synchronise les valeurs');
        if(route==='ajout_multi.php') {
            await evaluate(`document.querySelector('#multi-options').open=true`);
            fs.writeFileSync(path.join(folder,'checkboxes.png'),Buffer.from((await send('Page.captureScreenshot',{captureBeyondViewport:true})).data,'base64'));
            await evaluate(`document.querySelector('#multi-options').open=false`);
        }
        await evaluate(`for(const id of ['origin_key','extra_key']) { const s=document.getElementById(id);s.selectedIndex=1;s.dispatchEvent(new Event('change',{bubbles:true})); }`);
        await until(`!document.querySelector('#duplicates-choices').hidden`);
        await evaluate(`document.querySelector('#key_ignore').value='.';document.querySelector('#key_ignore').dispatchEvent(new Event('input',{bubbles:true}));`);
        await until(`!document.querySelector('#duplicates-choices').hidden`);
        const submit = route==='ajout_multi.php' ? '#multi-submit' : '#enrich-submit';
        const notice = route==='ajout_multi.php' ? '#multi-status' : '#enrich-status';
        assert.equal(await evaluate(`document.querySelector('${submit}').disabled`),true,'Choix des doublons obligatoire');
        await evaluate(`document.querySelector('#duplicate_mode').value='color';document.querySelector('#duplicate_mode').dispatchEvent(new Event('change',{bubbles:true}));`);
        assert.equal(await evaluate(`document.querySelector('${submit}').disabled`),true,'Occurrence obligatoire');
        await evaluate(`document.querySelector('#duplicate_occurrence').value='complete';document.querySelector('#duplicate_occurrence').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('${submit}').click()`);
        await until(`document.querySelector('${notice}').dataset.tone==='success'`);
        await evaluate(`document.querySelector('#duplicate_mode').value='delete';document.querySelector('#duplicate_mode').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('${submit}').click()`);
        await until(`document.querySelector('${notice}').dataset.tone==='success'`);
    }
    for (const route of ['impression_mono.php','impression_multi.php']) {
        await open(route); await upload('#excel',[fixture]);
        await until(`document.querySelector('#file-status').dataset.tone==='success'`);
        assert.equal(await evaluate(`document.querySelector('#print-options').open`),false,'Options impression repliées');
        assert.equal(await evaluate(`document.querySelector('#repeat_header').value`),'1','En-têtes répétés par défaut');
        await evaluate(`document.querySelector('#print-submit').click()`);
        await until(`document.querySelector('#print-status').dataset.tone==='success'`);
        await evaluate(`document.querySelector('#print-options').open=true;document.querySelector('#repeat_header').value='0'`);
        assert.equal(await evaluate(`document.querySelectorAll('#print-columns input:checked').length`),2,'Colonnes à préparer');
        await evaluate(`document.querySelector('#print-columns input').checked=false;document.querySelector('#print-columns').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('#print-submit').click()`);
        await until(`document.querySelector('#print-status').dataset.tone==='success'`);
        assert.match(await evaluate(`document.querySelector('#print-status').textContent`),/1 feuille\(s\) préparée/);
    }
    await open('fusion.php');
    await upload('input[name=x]', [fixture]); await upload('input[name=y]', [partialFixture]);
    await until(`document.querySelector('#fusion-status').dataset.tone === 'success'`);
    assert.equal(await evaluate(`document.querySelectorAll('#fusion-columns input:checked').length`), 4);
    await evaluate(`for (const panel of document.querySelectorAll('#fusion-columns fieldset')) { const inputs = [...panel.querySelectorAll('input')]; inputs.forEach((input, i) => input.checked = i === 0); inputs[0].dispatchEvent(new Event('change',{bubbles:true})); } document.querySelector('#fusion-form details > summary').click(); document.querySelector('#fusion-separator').value='0'; document.querySelector('#fusion-header').value='0'; document.querySelector('#fusion-submit').click()`);
    await until(`document.querySelector('#fusion-status').dataset.tone === 'success'`);
    assert.match(await evaluate(`document.querySelector('#fusion-status').textContent`), /Fusion terminée/);
    await evaluate(`document.querySelector('#fusion-columns input:checked').checked=false;document.querySelector('#fusion-columns').dispatchEvent(new Event('change',{bubbles:true}))`);
    assert.equal(await evaluate(`document.querySelector('#fusion-submit').disabled`), true, 'Fusion sans colonne bloquée');
    await open('enrichissement.php');
    const bad = path.join(folder, 'invalide.txt'); fs.writeFileSync(bad, 'test');
    await upload('#origin', [bad]);
    await until(`document.querySelector('#origin_status').dataset.tone === 'error'`);
    await until(`!document.querySelector('.error-summary').hidden`);
    assert.equal(await evaluate(`document.querySelector('#origin').getAttribute('aria-invalid')`),'true','Erreur près du champ');
    assert.equal(await evaluate(`document.querySelector('#enrich-submit').disabled`), true);
    await upload('#origin', [fixture]); await upload('#extra', [fixture]);
    await until(`document.querySelector('#origin_status').dataset.tone === 'success' && document.querySelector('#extra_status').dataset.tone === 'success'`);
    assert.equal(await evaluate(`document.querySelector('#add_column').selectedOptions.length`), 2, 'Toutes les colonnes du complément sélectionnées');
    await evaluate(`for (const [name,value] of [['origin_key','A'],['extra_key','A'],['add_column','B']]) { const field = document.getElementById(name); field.value=value; field.dispatchEvent(new Event('change',{bubbles:true})); }`);
    await until(`!document.querySelector('#enrich-submit').disabled`);
    assert.match(await evaluate(`document.querySelector('#mapping-summary').textContent`), /Salaire/);
    assert.equal(await evaluate(`document.querySelector('#insert_before').value`), '', 'Ajout en fin par défaut');
    await evaluate(`document.querySelector('#insert_before').value='A';document.querySelector('#insert_before').dispatchEvent(new Event('change',{bubbles:true}))`);
    assert.match(await evaluate(`document.querySelector('#mapping-summary').textContent`), /Avant A/);
    await evaluate(`document.querySelector('#origin_header').value='5';document.querySelector('#origin_header').dispatchEvent(new Event('input',{bubbles:true}))`);
    await until(`document.querySelector('#origin_status').dataset.tone === 'error'`);
    assert.equal(await evaluate(`document.querySelector('#enrich-submit').disabled`), true);
    await evaluate(`document.querySelector('#origin_header').value='1';document.querySelector('#origin_header').dispatchEvent(new Event('input',{bubbles:true}))`);
    await until(`document.querySelector('#origin_status').dataset.tone === 'success'`);
    const token = await evaluate(`document.querySelector('[name=csrf_token]').value`);
    await evaluate(`document.querySelector('#origin_key').value='A';document.querySelector('#origin_key').dispatchEvent(new Event('change',{bubbles:true}))`);
    await until(`!document.querySelector('#enrich-submit').disabled`);
    await evaluate(`document.querySelector('[name=csrf_token]').value='invalid';document.querySelector('#enrich-submit').click()`);
    await until(`document.querySelector('#enrich-status').dataset.tone === 'error'`);
    assert.equal(await evaluate(`document.querySelector('#origin').files.length`), 1, 'Fichier conservé après erreur');
    assert.equal(await evaluate(`document.querySelector('#enrich-submit').disabled`), false, 'Nouvel essai possible');
    await send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: folder });
    await evaluate(`document.querySelector('[name=csrf_token]').value=${JSON.stringify(token)};document.querySelector('#enrich-submit').click()`);
    await until(`document.querySelector('#enrich-status').dataset.tone === 'success'`);
    assert.match(await evaluate(`document.querySelector('#enrich-status').textContent`), /1 ligne\(s\) correspondante/);
    await evaluate(`document.querySelector('#add-all').click()`);
    await until(`!document.querySelector('#enrich-submit').disabled`);
    await evaluate(`document.querySelector('#enrich-submit').click()`);
    await until(`document.querySelector('#enrich-status').dataset.tone === 'success'`);
    await send('Network.enable');
    await send('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
    await evaluate(`document.querySelector('#enrich-submit').click()`);
    await until(`document.querySelector('#enrich-status').dataset.tone === 'error'`);
    assert.match(await evaluate(`document.querySelector('#enrich-status').textContent`), /Connexion interrompue/);
    await send('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
    await open('regroupement.php');
    await evaluate(`document.querySelector('form').dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }))`);
    await until(`document.querySelector('form .status-box').dataset.tone === 'error'`);
    assert.equal(await evaluate(`location.pathname.endsWith('regroupement.php')`), true, 'Erreur affichée dans le formulaire');
    await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
    for (const page of ['index.php', 'extraction_mono.php', 'extraction_hybride.php', 'ajout_multi.php', 'impression_mono.php', 'impression_multi.php', 'eclatement.php', 'regroupement.php', 'fusion.php', 'enrichissement.php', 'rapport.php', 'archive.php', 'guide.php']) {
        await open(page);
        assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'), true, 'Mobile overflow: ' + page);
    }
    await open('enrichissement.php');
    await evaluate(`document.querySelector('.menu-toggle').click()`);
    assert.equal(await evaluate(`document.querySelector('.sidebar').inert`), false);
    await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' });
    assert.equal(await evaluate(`document.querySelector('.sidebar').inert`), true);
    fs.writeFileSync(path.join(folder, 'mobile.png'), Buffer.from((await send('Page.captureScreenshot', { captureBeyondViewport: true })).data, 'base64'));
    assert.deepEqual(errors, []);
    console.log('OK : 13 pages desktop/mobile, titres centrés, extraction mono/multi, clés distinctes, choix et placement, exports, enrichissement et erreurs. Captures : ' + folder);
    await send('Browser.close');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => { ws?.close(); browser.kill(); });
